export default interface Legislator {
    id: string,
    first_name: string,
    last_name: string,
    display_name: string,
    title: string,
    district: string,
    party_affiliation: string,
    committees?: string[],
    email?: string,
    phone?: string,
    office_address?: string,
    photo_url?: string,
    website_url?: string,
    social_media?: Record<string, string>,
    date_of_birth?: string,
    gender?: string,
    race_ethnicity?: string,
    education?: string,
    occupation?: string,
    term_start?: string,
    term_end?: string,
    is_active: boolean,
    voice_profile_id?: string,
    face_profile_id?: string,
    bio?: string,
    metadata?: Record<string, any>,
    created_at: string,
    updated_at: string
};